version: '3'
services:
  users_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    tty: true
